### ISSUE TITLE
How to track location in background and set other parameters?

### ISSUE THREAD

**Issue by shravansukumar** [IngeoSDK/ingeo-ios-sdk#3]
Hello,
Thanks for a great library. Just some questions, even though you support background tracking of location, I tried it and I'm not clear how to do it properly(I have added all the necessary messages in the `Info.plist`). 

Also, would it be possible to set a condition, like to track the location every 100 meters, or something where I fetch the location every 10 seconds. 
Thanks in advance.

**Comment by amitpdev** [comment]
Thanks for asking this. The benefit of using IngeoSDK is that you should not worry about background tracking anymore. It's algorithm is able to determine user activity in order to auto adjust the background or foreground location monitoring system. It's not a matter of fetching the location every x seconds, that would be wasteful if you're driving on a highway or sleeping, right?
So it's a matter of balancing battery consumption and location accuracy ALL the time, while walking, driving, cycling, sleeping, staying at home, etc.
If you've successfully integrated the SDK to your app, you should be getting timely and filtered  location points to your delegate. With iOS Simulator try location simulator on menu 'Debug' -> 'Location' -> 'Freeway Drive'.

**Comment by shravansukumar** [comment]
Hello,
We have been testing the SDK on some of the live devices, it works well for first 10 to 15 minutes, giving all the location point in the journey, but then it stops until you get the app back to the foreground. Do you think we're missing something? Or it the device killing the process? 
Just FYI, devices are fully charged and all permissions have been given. 
Thanks.

**Comment by amitpdev** [comment]
Have you enabled 'Location updates' on your app Capabilities?
Please pm me your Ingeo registered email at amit@ingeo.io.
